var magicstring2 = `
{
    "enchant_cost":{
        "book":{
            "0":1,
            "1":1,
            "2":1,
            "3":2,
            "4":1,
            "5":4,
            "6":2,
            "7":2,
            "8":2,
            "9":1,
            "10":1,
            "11":1,
            "12":1,
            "13":2,
            "14":2,
            "15":1,
            "16":4,
            "17":1,
            "18":2,
            "19":1,
            "20":2,
            "21":2,
            "22":4,
            "23":2,
            "24":2,
            "25":2,
            "26":2,
            "27":4,
            "28":4,
            "29":2,
            "30":2,
            "31":1,
            "32":4,
            "33":2,
            "34":1,
            "35":1,
            "36":4,
            "37":4,
            "38":2,
            "39":1,
            "40":2,
			"41":1,
			"42":2,
			"43":1,
			"44":1,
			"45":2,
			"46":1,
			"47":2,
			"48":2,
			"49":1,
			"50":2,
			"51":4,
			"52":1,
			"53":4,
			"54":1,
			"55":1,
			"56":1,
			"57":4,
			"58":1,
			"59":4,
			"60":4,
			"61":4,
			"62":1,
			"63":1,
			"64":1,
			"65":1,
			"66":1,
			"67":1,
			"68":1,
			"69":2,
			"70":1,
			"71":1,
            "1000":2
        },
        "item":{
            "0":1,
            "1":2,
            "2":2,
            "3":4,
            "4":2,
            "5":8,
            "6":4,
            "7":4,
            "8":4,
            "9":1,
            "10":2,
            "11":2,
            "12":2,
            "13":4,
            "14":4,
            "15":1,
            "16":8,
            "17":2,
            "18":4,
            "19":1,
            "20":4,
            "21":4,
            "22":8,
            "23":4,
            "24":4,
            "25":4,
            "26":4,
            "27":8,
            "28":8,
            "29":4,
            "30":4,
            "31":1,
            "32":8,
            "33":4,
            "34":1,
            "35":2,
            "36":8,
            "37":8,
            "38":4,
            "39":2,
            "40":4,
			"41":1,
			"42":2,
			"43":1,
			"44":1,
			"45":2,
			"46":1,
			"47":2,
			"48":2,
			"49":1,
			"50":2,
			"51":4,
			"52":1,
			"53":4,
			"54":1,
			"55":1,
			"56":1,
			"57":4,
			"58":1,
			"59":4,
			"60":4,
			"61":4,
			"62":1,
			"63":1,
			"64":1,
			"65":1,
			"66":1,
			"67":1,
			"68":1,
			"69":2,
			"70":1,
			"71":1,
            "1000":4
        }
    },
    "max_lv":{
        "0":4,
        "1":4,
        "2":4,
        "3":4,
        "4":4,
        "5":3,
        "6":3,
        "7":3,
        "8":1,
        "9":5,
        "10":5,
        "11":5,
        "12":2,
        "13":2,
        "14":3,
        "15":5,
        "16":1,
        "17":3,
        "18":3,
        "19":5,
        "20":2,
        "21":1,
        "22":1,
        "23":3,
        "24":3,
        "25":2,
        "26":1,
        "27":1,
        "28":1,
        "29":5,
        "30":3,
        "31":3,
        "32":1,
        "33":1,
        "34":4,
        "35":3,
        "36":3,
        "37":3,
        "38":4,
        "39":5,
        "40":3,
		"41":1,
		"42":1,
		"43":3,
		"44":1,
		"45":1,
		"46":2,
		"47":2,
		"48":1,
		"49":4,
		"50":3,
		"51":3,
		"52":4,
		"53":1,
		"54":3,
		"55":3,
		"56":5,
		"57":3,
		"58":1,
		"59":1,
		"60":3,
		"61":3,
		"62":3,
		"63":2,
		"64":2,
		"65":2,
		"66":1,
		"67":3,
		"68":3,
		"69":1,
		"70":3,
		"71":3,
        "1000":3
    },
    "raw":[
        [
            0,
            "protection",
            "iv",
            1,
            1
        ],
        [
            1,
            "fire_protection",
            "iv",
            2,
            1
        ],
        [
            2,
            "feather_falling",
            "iv",
            2,
            1
        ],
        [
            3,
            "blast_protection",
            "iv",
            4,
            2
        ],
        [
            4,
            "projectile_protection",
            "iv",
            2,
            1
        ],
        [
            5,
            "thorns",
            "iii",
            8,
            4
        ],
        [
            6,
            "respiration",
            "iii",
            4,
            2
        ],
        [
            7,
            "depth_strider",
            "iii",
            4,
            2
        ],
        [
            8,
            "aqua_affinity",
            "i",
            4,
            2
        ],
        [
            9,
            "sharpness",
            "v",
            1,
            1
        ],
        [
            10,
            "smite",
            "v",
            2,
            1
        ],
        [
            11,
            "bane_of_arthropods",
            "v",
            2,
            1
        ],
        [
            12,
            "knockback",
            "ii",
            2,
            1
        ],
        [
            13,
            "fire_aspect",
            "ii",
            4,
            2
        ],
        [
            14,
            "looting",
            "iii",
            4,
            2
        ],
        [
            15,
            "efficiency",
            "v",
            1,
            1
        ],
        [
            16,
            "silk_touch",
            "i",
            8,
            4
        ],
        [
            17,
            "unbreaking",
            "iii",
            2,
            1
        ],
        [
            18,
            "fortune",
            "iii",
            4,
            2
        ],
        [
            19,
            "power",
            "v",
            1,
            1
        ],
        [
            20,
            "punch",
            "ii",
            4,
            2
        ],
        [
            21,
            "flame",
            "i",
            4,
            2
        ],
        [
            22,
            "infinity",
            "i",
            8,
            4
        ],
        [
            23,
            "luck_of_the_sea",
            "iii",
            4,
            2
        ],
        [
            24,
            "lure",
            "iii",
            4,
            2
        ],
        [
            25,
            "frost_walker",
            "ii",
            4,
            2
        ],
        [
            26,
            "mending",
            "i",
            4,
            2
        ],
        [
            27,
            "curse_of_binding",
            "i",
            8,
            4
        ],
        [
            28,
            "curse_of_vanishing",
            "i",
            8,
            4
        ],
        [
            29,
            "impaling",
            "v",
            4,
            2
        ],
        [
            30,
            "riptide",
            "iii",
            4,
            2
        ],
        [
            31,
            "loyalty",
            "iii",
            1,
            1
        ],
        [
            32,
            "channeling",
            "i",
            8,
            4
        ],
        [
            33,
            "multishot",
            "i",
            4,
            2
        ],
        [
            34,
            "piercing",
            "iv",
            1,
            1
        ],
        [
            35,
            "quick_charge",
            "iii",
            2,
            1
        ],
        [
            36,
            "soul_speed",
            "iii",
            8,
            4
        ],
        [
            37,
            "swift_sneak",
            "iii",
            8,
            4
        ],
        [
            38,
            "breach",
            "iv",
            4,
            2
        ],
        [
            39,
            "density",
            "v",
            2,
            1
        ],
        [
            40,
            "wind_burst",
            "iii",
            4,
            2
        ],
		[
            41,
            "lavawaxed",
            "i",
            1,
            1
        ],
		[
            42,
            "serpent_charmer",
            "i",
            2,
            2
        ],
		[
            43,
            "straddle_jump",
            "iii",
            1,
            1
        ],
		[
            44,
            "returning_board",
            "i",
            1,
            1
        ],
		[
            45,
            "alleviating",
            "i",
            2,
            2
        ],
		[
            46,
            "launch",
            "ii",
            1,
            1
        ],
		[
            47,
            "reeling",
            "ii",
            2,
            2
        ],
		[
            48,
            "reforming",
            "i",
            2,
            2
        ],
		[
            49,
            "shockwave",
            "iiii",
            1,
            1
        ],
		[
            50,
            "spread_of_ailments",
            "iii",
            2,
            2
        ],
		[
            51,
            "vengeance",
            "iii",
            4,
            4
        ],
		[
            52,
            "spell_reflection",
            "iiii",
            1,
            1
        ],
		[
            53,
            "soulbound",
            "i",
            4,
            4
        ],
		[
            54,
            "mana_regen",
            "iii",
            1,
            1
        ],
		[
            55,
            "mana_boost",
            "iii",
            1,
            1
        ],
		[
            56,
            "sculk_smite",
            "iiiii",
            1,
            1
        ],
		[
            57,
            "catalysis",
            "iii",
            4,
            4
        ],
		[
            58,
            "chopper",
            "i",
            1,
            1
        ],
		[
            59,
            "enfeeble",
            "i",
            4,
            4
        ],
		[
            60,
            "sustain",
            "iii",
            4,
            4
        ],
		[
            61,
            "rupture",
            "iii",
            4,
            4
        ],
		[
            62,
            "bounce",
            "iii",
            1,
            1
        ],
		[
            63,
            "rebound",
            "iii",
            1,
            1
        ],
		[
            64,
            "haunted",
            "ii",
            1,
            1
        ],
		[
            65,
            "spirit_plunder",
            "ii",
            1,
            1
        ],
		[
            66,
            "replenishing",
            "i",
            1,
            1
        ],
		[
            67,
            "fire_react",
            "iii",
            1,
            1
        ],
		[
            68,
            "chill_aura",
            "iii",
            1,
            1
        ],
		[
            69,
            "self_sling",
            "i",
            2,
            2
        ],
		[
            70,
            "ricochet",
            "iii",
            1,
            1
        ],
		[
            71,
            "longevity",
            "iii",
            1,
            1
        ],
		[
            1000,
            "sweeping_edge",
            "iii",
            1,
            1
        ]
    ],
    "conflicts":{
        "0":[
            1,
            3,
            4
        ],
        "1":[
            0,
            3,
            4
        ],
        "3":[
            0,
            1,
            4
        ],
        "4":[
            0,
            1,
            3
        ],
        "7":[
            25
        ],
        "9":[
            10,
            11,
			56
        ],
        "10":[
            9,
            11,
            38,
            39,
			56
        ],
        "11":[
            9,
            10,
            38,
            39,
			56
        ],
		"56":[
            9,
			10,
			11,
			38,
			39
        ],
        "16":[
            18
        ],
        "18":[
            16
        ],
        "22":[
            26,
			48
        ],
		"48":[
            22,
			26
        ],
        "25":[
            7
        ],
        "26":[
            22,
			48
        ],
        "30":[
            31,
            32
        ],
        "31":[
            30
        ],
        "32":[
            30
        ],
        "33":[
            34
        ],
        "34":[
            33
        ],
        "38":[
            10,
            11,
            39
        ],
        "39":[
            10,
            11,
            38
        ]
		"67":[
            68
        ],
		"68":[
            67
        ]
    },
    "idmap":{
        "0":"protection",
        "1":"fire_protection",
        "2":"feather_falling",
        "3":"blast_protection",
        "4":"projectile_protection",
        "5":"thorns",
        "6":"respiration",
        "7":"depth_strider",
        "8":"aqua_affinity",
        "9":"sharpness",
        "10":"smite",
        "11":"bane_of_arthropods",
        "12":"knockback",
        "13":"fire_aspect",
        "14":"looting",
        "15":"efficiency",
        "16":"silk_touch",
        "17":"unbreaking",
        "18":"fortune",
        "19":"power",
        "20":"punch",
        "21":"flame",
        "22":"infinity",
        "23":"luck_of_the_sea",
        "24":"lure",
        "25":"frost_walker",
        "26":"mending",
        "27":"curse_of_binding",
        "28":"curse_of_vanishing",
        "29":"impaling",
        "30":"riptide",
        "31":"loyalty",
        "32":"channeling",
        "33":"multishot",
        "34":"piercing",
        "35":"quick_charge",
        "36":"soul_speed",
        "37":"swift_sneak",
        "38":"breach",
        "39":"density",
        "40":"wind_burst",
		"41":"lavawaxed",
		"42":"serpent_charmer",
		"43":"straddle_jump",
		"44":"returning_board",
		"45":"alleviating",
		"46":"launch",
		"47":"reeling",
		"48":"reforming",
		"49":"shockwave",
		"50":"spread_of_ailments",
		"51":"vengeance",
		"52":"spell_reflection",
		"53":"soulbound",
		"54":"mana_regen",
		"55":"mana_boost",
		"56":"sculk_smite",
		"57":"catalysis",
		"58":"chopper",
		"59":"enfeeble",
		"60":"sustain",
		"61":"rupture",
		"62":"bounce",
		"63":"rebound",
		"64":"haunted",
		"65":"spirit_plunder",
		"66":"replenishing",
		"67":"fire_react",
		"68":"chill_aura",
		"69":"self_sling",
		"70":"ricochet",
		"71":"longevity",
        "1000":"sweeping_edge",
        "protection":0,
        "fire_protection":1,
        "feather_falling":2,
        "blast_protection":3,
        "projectile_protection":4,
        "thorns":5,
        "respiration":6,
        "depth_strider":7,
        "aqua_affinity":8,
        "sharpness":9,
        "smite":10,
        "bane_of_arthropods":11,
        "knockback":12,
        "fire_aspect":13,
        "looting":14,
        "efficiency":15,
        "silk_touch":16,
        "unbreaking":17,
        "fortune":18,
        "power":19,
        "punch":20,
        "flame":21,
        "infinity":22,
        "luck_of_the_sea":23,
        "lure":24,
        "frost_walker":25,
        "mending":26,
        "curse_of_binding":27,
        "curse_of_vanishing":28,
        "impaling":29,
        "riptide":30,
        "loyalty":31,
        "channeling":32,
        "multishot":33,
        "piercing":34,
        "quick_charge":35,
        "soul_speed":36,
        "swift_sneak":37,
        "breach":"38",
        "density":"39",
        "wind_burst":"40",
		"lavawaxed":41,
		"serpent_charmer":42,
		"straddle_jump":43,
		"returning_board":44,
		"alleviating":45,
		"launch":46,
		"reeling":47,
		"reforming":48,
		"shockwave":49,
		"spread_of_ailments":50,
		"vengeance":51,
		"spell_reflection":52,
		"soulbound":53,
		"mana_regen":54,
		"mana_boost":55,
		"sculk_smite":56,
		"catalysis":57,
		"chopper":58,
		"enfeeble":59,
		"sustain":60,
		"rupture":61,
		"bounce":62,
		"rebound":63,
		"haunted":64,
		"spirit_plunder":65,
		"replenishing":66,
		"fire_react":67,
		"chill_aura":68,
		"self_sling":69,
		"ricochet":70,
		"longevity":71,
		"sweeping_edge":1000,
    },
    "enchantable":{
        "0":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "turtle_shell"
        ],
        "1":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "turtle_shell"
        ],
        "2":[
            "boots"
        ],
        "3":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "turtle_shell"
        ],
        "4":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "turtle_shell"
        ],
        "5":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "turtle_shell"
        ],
        "6":[
            "helmet",
            "turtle_shell"
        ],
        "7":[
            "boots"
        ],
        "8":[
            "helmet",
            "turtle_shell"
        ],
        "9":[
            "sword",
            "axe"
        ],
        "10":[
            "sword",
            "axe",
            "mace"
        ],
        "11":[
            "sword",
            "axe",
            "mace"
        ],
        "12":[
            "sword"
        ],
        "13":[
            "sword",
            "mace"
        ],
        "14":[
            "sword"
        ],
        "15":[
            "pickaxe",
            "shovel",
            "axe",
            "hoe",
            "shears"
        ],
        "16":[
            "pickaxe",
            "shovel",
            "axe",
            "hoe"
        ],
        "17":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "pickaxe",
            "shovel",
            "axe",
            "sword",
            "hoe",
            "fishing_rod",
            "bow",
            "shears",
            "flint_and_steel",
            "carrot_on_a_stick",
            "warped_fungus_on_a_stick",
            "shield",
            "elytra",
            "trident",
            "turtle_shell",
            "crossbow",
            "mace"
        ],
        "18":[
            "pickaxe",
            "shovel",
            "axe",
            "hoe"
        ],
        "19":[
            "bow"
        ],
        "20":[
            "bow"
        ],
        "21":[
            "bow"
        ],
        "22":[
            "bow"
        ],
        "23":[
            "fishing_rod"
        ],
        "24":[
            "fishing_rod"
        ],
        "25":[
            "boots"
        ],
        "26":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "pickaxe",
            "shovel",
            "axe",
            "sword",
            "hoe",
            "fishing_rod",
            "bow",
            "shears",
            "flint_and_steel",
            "carrot_on_a_stick",
            "warped_fungus_on_a_stick",
            "shield",
            "elytra",
            "trident",
            "turtle_shell",
            "crossbow",
            "mace"
        ],
        "27":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "elytra",
            "turtle_shell"
        ],
        "28":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "pickaxe",
            "shovel",
            "axe",
            "sword",
            "hoe",
            "fishing_rod",
            "bow",
            "shears",
            "flint_and_steel",
            "carrot_on_a_stick",
            "warped_fungus_on_a_stick",
            "shield",
            "elytra",
            "helmet",
            "trident",
            "turtle_shell",
            "crossbow",
            "mace"
        ],
        "29":[
            "trident"
        ],
        "30":[
            "trident"
        ],
        "31":[
            "trident"
        ],
        "32":[
            "trident"
        ],
        "33":[
            "crossbow"
        ],
        "34":[
            "crossbow"
        ],
        "35":[
            "crossbow"
        ],
        "36":[
            "boots"
        ],
        "37":[
            "leggings"
        ],
        "38":[
            "mace"
        ],
        "39":[
            "mace"
        ],
        "40":[
            "mace"
        ],
		"41":[
            "straddleboard"
        ],
		"42":[
            "straddleboard"
        ],
		"43":[
            "straddleboard"
        ],
		"44":[
            "straddleboard"
        ],
		"45":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "elytra",
            "turtle_shell"
        ],
		"46":[
            "sword"
        ],
		"47":[
            "crossbow"
        ],
		"48":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "pickaxe",
            "shovel",
            "axe",
            "sword",
            "hoe",
            "fishing_rod",
            "bow",
            "shears",
            "flint_and_steel",
            "carrot_on_a_stick",
            "warped_fungus_on_a_stick",
            "shield",
            "elytra",
            "trident",
            "turtle_shell",
            "crossbow",
            "mace"
        ],
		"49":[
            "boots"
        ],
		"50":[
            "crossbow"
        ],
		"51":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "elytra",
            "turtle_shell"
        ],
		"52":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "elytra",
            "turtle_shell"
        ],
		"53":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "pickaxe",
            "shovel",
            "axe",
            "sword",
            "hoe",
            "fishing_rod",
            "bow",
            "shears",
            "flint_and_steel",
            "carrot_on_a_stick",
            "warped_fungus_on_a_stick",
            "shield",
            "elytra",
            "trident",
            "turtle_shell",
            "crossbow",
            "mace"
        ],
		"54":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "elytra",
            "turtle_shell"
        ],
		"55":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "elytra",
            "turtle_shell"
        ],
		"56":[
            "sword",
            "axe",
            "mace"
        ],
		"57":[
            "sword",
            "axe",
            "mace"
        ],
		"58":[
            "axe"
        ],
		"59":[
            "tablet"
        ],
		"60":[
            "tablet"
        ],
		"61":[
            "tablet"
        ],
		"62":[
            "boomerang"
        ],
		"63":[
            "scythe"
        ],
		"64":[
            "scythe"
        ],
		"65":[
            "scythe"
        ],
		"66":[
            "scythe"
        ],
		"67":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "elytra",
            "turtle_shell"	
        ],
		"68":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "elytra",
            "turtle_shell"	
        ],
		"69":[
            "slingshot"
        ],
		"40":[
            "slingshot"
        ],
		"40":[
            "slingshot"
        ],
        "1000":[
            "sword"
        ]
    },
    "enchantbytool":{
        "helmet":[
            "0",
            "1",
            "3",
            "4",
            "5",
            "6",
            "8",
            "17",
            "26",
            "27",
            "28",
			"45",
			"48",
			"51",
			"52",
			"53",
			"54",
			"55",
			"67",
			"68"
        ],
        "chestplate":[
            "0",
            "1",
            "3",
            "4",
            "5",
            "17",
            "26",
            "27",
            "28",
			"45",
			"48",
			"51",
			"52",
			"53",
			"54",
			"55",
			"67",
			"68"
        ],
        "leggings":[
            "0",
            "1",
            "3",
            "4",
            "5",
            "17",
            "26",
            "27",
            "28",
            "37",
			"45",
			"48",
			"51",
			"52",
			"53",
			"54",
			"55",
			"67",
			"68"
        ],
        "boots":[
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "7",
            "17",
            "25",
            "26",
            "27",
            "28",
            "36",
			"45",
			"48",
			"51",
			"52",
			"53",
			"54",
			"55",
			"67",
			"68",
			"49"
        ],
        "turtle_shell":[
            "0",
            "1",
            "3",
            "4",
            "5",
            "6",
            "8",
            "17",
            "26",
            "27",
            "28",
			"45",
			"48",
			"51",
			"52",
			"53",
			"54",
			"55",
			"67",
			"68"
        ],
        "sword":[
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "17",
            "26",
            "28",
			"46",
            "53",
            "56",
            "57",
            "1000"
        ],
        "axe":[
            "9",
            "10",
            "11",
            "15",
            "16",
            "17",
            "18",
            "26",
            "28",
			"46",
			"48",
            "53",
            "56",
            "57",
			"58"
        ],
        "pickaxe":[
            "15",
            "16",
            "17",
            "18",
            "26",
            "28",
			"46",
			"48",
            "53",
            "56",
            "57",
        ],
        "shovel":[
            "15",
            "16",
            "17",
            "18",
            "26",
            "28",
			"46",
			"48",
            "53",
            "56",
            "57",
        ],
        "hoe":[
            "15",
            "16",
            "17",
            "18",
            "26",
            "28",
			"46",
			"48",
            "53",
            "56",
            "57",
        ],
        "shears":[
            "15",
            "17",
            "26",
            "28",
			"48",
			"53"
        ],
        "fishing_rod":[
            "17",
            "23",
            "24",
            "26",
            "28",
			"48",
			"53"
        ],
        "bow":[
            "17",
            "19",
            "20",
            "21",
            "22",
            "26",
            "28",
			"48",
			"53"
        ],
        "flint_and_steel":[
            "17",
            "26",
            "28",
			"48",
			"53"
        ],
        "carrot_on_a_stick":[
            "17",
            "26",
            "28",
			"48",
			"53"
        ],
        "warped_fungus_on_a_stick":[
            "17",
            "26",
            "28",
			"48",
			"53"
        ],
        "shield":[
            "17",
            "26",
            "28",
			"48",
			"53"
        ],
        "elytra":[
            "17",
            "26",
            "27",
            "28",
			"48",
			"53"
        ],
		"scythe":[
            "17",
            "26",
            "27",
            "28",
			"48",
			"53",
			"63",
			"64"
        ],
        "boomerang":[
            "17",
            "26",
            "27",
            "28",
			"48",
			"53",
			"62"
        ],
		"slingshot":[
            "69",
            "70",
            "71",
            "53",
			"48",
			"53"
        ],
        "trident":[
            "17",
            "26",
            "28",
            "29",
            "30",
            "31",
            "32",
			"48",
			"53"
        ],
        "crossbow":[
            "17",
            "26",
            "28",
            "33",
            "34",
            "35",
			"48",
			"47",
			"50",
			"53"
        ],
        "mace":[
            "10",
            "11",
            "13",
            "17",
            "26",
            "28",
            "38",
            "39",
            "40",
			"48",
			"53"
        ],
        "enchanted_book":[
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31",
            "32",
            "33",
            "34",
            "35",
            "36",
            "37",
            "1000"
        ]
    }
}
`
